const ServerToClientRpcMap = {
	PartyKey: { partyKey: "String" },
	PartyBuilding: {
		isArray: true,
		dead: "Boolean",
		tier: "Uint8",
		type: "String",
		uid: "Uint32",
		x: "Uint32",
		y: "Uint32",
		yaw: "Uint16",
	},
	PartyRequest: { name: "String", uid: "Uint32" },
	PartyRequestCancelled: { uid: "Uint32" },
	PartyRequestMet: {},
	PartyMembersUpdated: {
		isArray: true,
		canPlace: "Boolean",
		canSell: "Boolean",
		name: "String",
		uid: "Uint32",
		isLeader: "Boolean",
	},
	UpdateParty: {
		isArray: true,
		isOpen: "Boolean",
		partyId: "Uint32",
		partyName: "String",
		memberCount: "Uint8",
		memberLimit: "Uint8",
	},
	UpdateLeaderboard: {
		isArray: true,
		uid: "Uint32",
		name: "String",
		score: "Uint64",
		wave: "Uint64",
		rank: "Uint8",
	},
	UpdateDayNightCycle: { nightLength: "Uint32", dayLength: "Uint32" },
	Respawned: {},
	SetTool: { isArray: true, toolName: "String", toolTier: "Uint8" },
	Dead: { reason: "String", wave: "Uint64", score: "Uint64", partyScore: "Uint64" },
	ToolInfo: { json: "String" },
	BuildingInfo: { json: "String" },
	SpellInfo: { json: "String" },
	CastSpellResponse: { name: "String", cooldown: "Uint32", iconCooldown: "Uint32" },
	ClearActiveSpell: { name: "String" },
	EntityData: { json: "String" },
	Failure: { failure: "String" },
	ReceiveChatMessage: { channel: "String", name: "String", message: "String" },
	DamageDealt: { x: "Uint16", y: "Uint16", damage: "Int32" },
	EntityKilled: { uid: "Uint32", score: "OptionalUint32" },
	LightningZap: { isArray: true, x: "Uint16", y: "Uint16" },
	SetTickRate: { tickRate: "Float", serverSpeed: "Uint8" },
	AdminCommandResponse: { json: "String" },
};

export default ServerToClientRpcMap;
